env:
  browser: false
  node: true
  es6: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-unused-vars:
    - "error"
    - { "argsIgnorePattern": "^_" }
  require-atomic-updates: "off" # TODO enable